site_name: feiyan.help
site_url: https://feiyan.help
site_author: Chinese
site_description: Support the City of WuHan
copyright: Open source under GNU GPL v3.0

repo_name: feiyan.help
repo_url: https://github.com/wuhan-support/wuhan.support

nav:
  # 现状
  - 主页: index.md
  # 如何就诊
  - 发热门诊定点机构:
    - 就诊: hospitals/index.md
    - 湖北省:
      - 湖北省: hospitals/hubei.md
      - 武汉市: hospitals/hubei/wuhan.md
      - 黄石市: hospitals/hubei/huangshi.md
      - 十堰市: hospitals/hubei/shiyan.md
      - 荆州市: hospitals/hubei/jingzhou.md
      #- 宜昌市: hospitals/hubei/yichang.md
      - 襄阳市: hospitals/hubei/xiangyang.md
      - 鄂州市: hospitals/hubei/ezhou.md
      - 荆门市: hospitals/hubei/jingmen.md
      - 黄冈市: hospitals/hubei/huanggang.md
      - 孝感市: hospitals/hubei/xiaogan.md
      - 咸宁市: hospitals/hubei/xianning.md
      - 仙桃市: hospitals/hubei/xiantao.md
      - 潜江市: hospitals/hubei/qianjiang.md
      - 神农架林区: hospitals/hubei/shennongjia.md
      - 恩施土家族苗族自治州发: hospitals/hubei/enshi.md
      - 天门市: hospitals/hubei/tianmen.md
      - 随州市 : hospitals/hubei/suizhou.md
    - 甘肃省:
      - 甘肃省: hospitals/gansu.md
      - 兰州市: hospitals/gansu/lanzhou.md
      #- 嘉峪关市: hospitals/gansu/jiayuguan.md
      - 金昌市: hospitals/gansu/jinchang.md
      - 白银市: hospitals/gansu/baiyin.md
      - 天水市: hospitals/gansu/tianshui.md
      - 酒泉市: hospitals/gansu/jiuquan.md
      - 张掖市: hospitals/gansu/zhangye.md
      - 武威市: hospitals/gansu/wuwei.md
      - 定西市: hospitals/gansu/dingxi.md
      - 陇南市: hospitals/gansu/longnan.md
      - 平凉市: hospitals/gansu/pingliang.md
      - 庆阳市: hospitals/gansu/qingyang.md
      - 临夏市: hospitals/gansu/linxia.md
      - 甘南市: hospitals/gansu/gannan.md
  # 如何捐赠
  - 医护人员免费住宿:
    - 武汉大陆坊自如驿: hotels/dlfzry.md
  - 捐赠渠道:
    - 主要渠道: donate/index.md
    - 武汉市:
      - 华中科技大学同济医学院附属协和医院: donate/whuh.md
      - 武汉市中心医院: donate/chw.md
      - 武汉大学人民医院: donate/rmhwu.md
      - 武汉大学中南医院: donate/znhwu.md
      - 武汉市第一医院: donate/no.1hw.md
      - 武汉市儿童医院: donate/wch.md
      - 湖北省中医院: donate/whtc.md
  # 如何防护
  - 预防手册: protection/index.md
  # 与开发者沟通交流或者成为开发者
  - 贡献: 
      - 贡献: contribution/index.md
      - 贡献数据: contribution/data.md


theme:
  name: material
  language: 'zh'
  palette:
    primary: 'deep purple'
    accent: 'amber'
  logo: 'images/logo.png'
  feature:
    tabs: true
  font:
    text: 'Noto Sans'
    code: 'Cascadia Code'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/wuhan-support/'
  disqus: 'wuhan-support'

extra_css:
    - css/css.css
    #- css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-104387513-2'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - mdx_math
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"

plugins:
  - search
  - awesome-pages
  # - git-committers
